export const iconNames = ['tennis-ball',
 'tennis',
 'dice-3-outline', 
 'handball', 
 'football-helmet', 
 'glass-mug-variant', 
 'table-tennis', 
 'golf-cart',
 'karate',
 'cards',
 'microsoft-xbox-controller',
 'basketball',
 'bowling', 
 'snake',
 'wizard-hat'
]